CAN_ID_SETPOINT_CMD = 0x100
CAN_ID_MEASUREMENT_FB = 0x101
CAN_ID_CONTROL_OUTPUT = 0x102
CAN_ID_STATUS = 0x103
CAN_ID_HEARTBEAT = 0x104

CAN_DLC_SETPOINT_CMD = 8
CAN_DLC_MEASUREMENT_FB = 8
CAN_DLC_CONTROL_OUTPUT = 8
CAN_DLC_STATUS = 8
CAN_DLC_HEARTBEAT = 8

CAN_SCALE_DENOMINATOR = 1000

CAN_STATE_INIT = 0
CAN_STATE_READY = 1
CAN_STATE_RUNNING = 2
CAN_STATE_ERROR = 3
CAN_STATE_FINISHED = 4

CAN_NODE_ID_CONTROLLER = 1
CAN_NODE_ID_PLANT = 2
CAN_NODE_ID_ORCH = 3

